@baseUrl = http://localhost:3000

# RECADOS

###
GET {{baseUrl}}/recados/?limit=10&offset=12
###

###
GET {{baseUrl}}/recados/2/
###

###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "NOVO recado de teste",
  "de": "Joana",
  "para": "João",
  "lido": false,
  "data": "2025-12-23T19:35:31.883Z"
}
###

###
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

{
  "texto": "ATUALIZAR O RECADO 2",
  "de": "Joana",
  "para": "João",
  "lido": false,
  "data": "2025-12-23T19:35:31.883Z"
}
###

###
DELETE  {{baseUrl}}/recados/2
###
