@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

# RECADOS

###
GET {{baseUrl}}/recados/?limit=10&offset=0
Authorization: Bearer {{authToken}}
###

###
GET {{baseUrl}}/recados/18/
###

###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "Recado Novo",
  "deId": 8,
  "paraId": 9
}
###

###
PATCH {{baseUrl}}/recados/17
Content-Type: application/json

{
  "texto": "ATUALIZAR O RECADO 17",
  "lido": false
}
###

###
DELETE  {{baseUrl}}/recados/17
###


# Pessoas


###
GET {{baseUrl}}/pessoas/?limit=10&offset=12
Authorization: Bearer {{authToken}}
###

###
GET {{baseUrl}}/pessoas/8/
Authorization: Bearer {{authToken}}
###

###
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "kauan@emailteste.com",
  "nome": "KAUAN Fiolo",
  "password": "123456"
}
###

###
PATCH {{baseUrl}}/pessoas/15
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "nome": "kauan"
}
###

###
DELETE  {{baseUrl}}/pessoas/13
Authorization: Bearer {{authToken}}
###


# Auth


###
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "kauan@emailteste.com",
  "password": "123456"
}
###