@baseUrl = http://localhost:3000

# RECADOS

###
GET {{baseUrl}}/recados/?limit=10&offset=12
###

###
GET {{baseUrl}}/recados/4/
###

###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "Recado",
  "deId": 7,
  "paraId": 8
}
###

###
PATCH {{baseUrl}}/recados/3
Content-Type: application/json

{
  "texto": "ATUALIZAR O RECADO 3",
  "lido": true
}
###

###
DELETE  {{baseUrl}}/recados/2
###






# Pessoas

###
GET {{baseUrl}}/pessoas/?limit=10&offset=12
###

###
GET {{baseUrl}}/pessoas/2/
###

###
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "email@email2.com",
  "nome": "kauan",
  "password": "123456"
}
###

###
PATCH {{baseUrl}}/pessoas/7
Content-Type: application/json

{
  "nome": "nauak",
  "password": "654321"
}
###

###
DELETE  {{baseUrl}}/pessoas/1
###